name: Update Schedule

on:
  schedule:
    - cron: '0 15 * * 3'
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  update_schedule:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update schedule
      run: swift run MotorsportCalendar --output ./data --formula1-calendar-url ${{ secrets.FORMULA_1_CALENDAR_URL }}

    - name: Check for changes
      id: changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Changes detected"
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "No changes detected"
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git checkout -b auto/update-schedule
        git add -A
        git commit -m "Update schedule"
        git push origin auto/update-schedule --force

    - name: Create Pull Request
      if: steps.changes.outputs.changed == 'true'
      run: |
        changes="# Changes\n\n"
        for file in $(git --no-pager diff HEAD~1 HEAD --name-only); do
          changes+="<details><summary>$file</summary>\n\n\`\`\`diff\n"
          changes+=$(diff -u <(git --no-pager show HEAD~1:$file | jq) <(git --no-pager show HEAD:$file | jq))
          changes+="\n\`\`\`\n</details>\n\n"
        done

        echo "$changes" | gh pr create --title "Update schedule" --body-file -
